config/routes.rb
Rails.application.routes.draw do
  resources 'registrations'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :show, :create]
  resources :sessions, only:[:new, :create, :destroy]
  resources :events
  resources :event_enrolment, only: [ :create, :destroy, :update ]
  scope :sessions do
    get 'signup', to: 'users#new'
    get 'login', to: 'sessions#new', as: 'login'
    get 'signout', to: 'sessions#destroy'
  end

  
  root 'events#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User'
  has_many :registrations
  has_many :attendees, through: :registrations, source: :user

  scope :upcoming_events, -> { where('date >= ?', Time.now) }
  scope :previous_events, -> { where('date <  ?', Time.now) }

  validates :date, presence: true
  validates :name, presence: true
end

app/models/registration.rb
class Registration < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  has_one :session
  has_many :events, foreign_key: :creator_id
  has_many :registrations
  # has_many :user_registrations, through: :registrations, source: :events
  has_many :attended_events, through: :registrations, source: :user

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include EventsHelper
  before_action :require_session, except: [:index]
  before_action :creator?, only: %i[edit destroy]

  def index
    @event = Event.all
    @upcoming_events = Event.upcoming_events
    @previous_events = Event.previous_events
  end

  def new
    @event = Event.new
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    set_event
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      flash[:success] = "Event '#{@event.name}' created!"
      redirect_to user_path(current_user.id)
    else
      flash[:alert] = @event.errors
      render 'new'
    end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :date)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  include RegistrationsHelper
  def new
    @invitation = Registration.new
  end

  def create
    @invitation = Registration.create(registratation_params)
    if @invitation.save
      redirect_to event_path(@invitation.event_id), notice: 'Invitation sent'
    else
      redirect_to event_path(@invitation.event_id), alert: 'Error creating invitation!'
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    @user = User.find_by_name(params[:name])
    if @user
      session[:user_id] = @user.id
      redirect_to user_path(current_user.id), notice: 'Signed in successfully!'
    else
      flash.now[:alert] = 'Username is invalid'
      render 'new'
    end
  end

  def destroy
    reset_session
    redirect_to root_url, notice: 'Signed out successfully!'
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save?
      redirect_to @user
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper

  before_action :require_session, except: %i[new create]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    # Set a session value
    if @user.save
      start_session(@user)
    else
      flash.notice = 'Error'
    end
  end

  def show
    @invited_events = User.find(params[:id]).attended_events
    # @upcoming_events = current_user.attended_events.upcoming
    # @previous_events = @invited_events.previous_events
    # @created_events = User.find(params[:id]).events
    @created_events = current_user.events
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end

  def require_session
    redirect_to new_user_path, alert: 'Sign Up or Sign In to access this feature!' unless current_user
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:name, :description, :location, :start_time, :end_time, :date, :user_id)
  end

  

  def render_index_events(related_events)
    if related_events
      title = 'Upcoming Events' if related_events == @upcoming_events
      title = 'Past Events' if related_events == @past_events
      render 'events/partials/event_index', related_events: related_events, title: title
    end
  end

  def render_invite_controls(event)
    render 'events/partials/invite_controls', event: event if event.creator == current_user
  end

  def creator?
    set_event
    return if current_user.id == @event.user_id

    flash[:alert] = 'Unauthorized request'
    redirect_to root_path
  end
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
  def registratation_params
    params.require(:registration).permit(:user, :event, :user_id, :event_id)
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def set_user
    @user = User.find(params[:id])
  end

  def start_session(user)
    if user
      session[:user_id] = user.id
      redirect_to user_path(current_user.id), notice: "User #{user.name} account signed up successfully!"
    else
      flash.now[:alert] = 'Username is invalid'
    end
  end

  def render_invitation_table(user)
    html_out = ''
    html_out << "<table class=\"table table-hover text-center align-middle\">
              <tbody><th>Name</th><th>Status</th><th>Action</th>
              <% @users.reject { |user| user == Event.find(params[:event_id]).creator }.each do |user| %>
              <% @event_enrolment = EventEnrolment.find_by(event_id: params[:event_id], user_id: user.id) %>
              <tr><td><%= user.name %></td>
              <% unless @event_enrolment.nil? || @event_enrolment.nil? %><td>
              <span class=\"tag is-primary is-medium is-light\"><%= @event_enrolment %></span>
              </td><% else %><td></td><% end %><% if @event_enrolment.nil? %><td>
              <%= button_to \"Invite\", event_enrolment_index_path(event_id: params[:event_id],
                               user_id: user.id), class: \"btn btn-sm btn-secondary w-75\" %>
              </td><% else %><td><%= button_to \"Cancel Invitation\", event_enrolment_path(id: @event_enrolment.id,
                       event_id: params[:event_id]), method: :delete, class: \"btn btn-sm btn-danger w-75 m-0\" %>
              </td><% end %></tr><% end %></tbody></table>
          <%= link_to 'Back', event_path(id: params[:event_id]), class: \"btn btn-light w-100 my-3\" %>"
    render inline: html_out, locals: { user: user }
  end
end

app/views/events/index.html.erb
<div class="container">
<h2>Past Events</h2>

  <% @previous_events.each do |event| %>
      <h4><%= event.name %></h4>
      <p><%= event.description %></p>
      <span><%= event.creator.name %></span>
      <h5><%= event.date%></h5>
  <% end %> 

</div>

<div class="container">
<h2>Upcoming Events</h2>
<% @upcoming_events.each do |event| %>  
      <h4><%= event.name %></h4>
      <p><%= event.description %></p>
      <span><%= event.creator.name %></span>
      <h5><%= event.date%></h5>
<% end %>
</div>

app/views/events/new.html.erb
<h1 class="text-center">Create your Event</h1>
  
    <%= form_for @event do |f| %>
    <div class="container">
      <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, required: true , class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :description %><br>
      <%= f.text_area :description, required: true, class: "form-control", id: "exampleFormControlTextarea1", rows: "3" %><br>
    </div>
    <div class="form-group">
      <%= f.label :date %>
      <%= f.date_field :date %><br>
    </div>
      <%= f.submit 'Create Event' %>
    </div>    
    <% end %>

app/views/events/show.html.erb
<div class="container">
  <h3><%= @event.name %></h3>
  <p><%= @event.description %></p>
  <h5><%= @event.date%></h5>
  <span><%= @event.creator.name %></span>

  <% if @event.registrations.empty? %>
    <p>Event has no events attendees</p>
  <% else %>
    <% @event.registrations.each do |registrations| %>
      <% current_user.events.each do |event| %>
        <h5 class = "card-title">Time: <%= event.date%><%= link_to "->", event_path(event) %></h5>
        <p class = "card-text ">Description: <%= event.description %> </p>
      <%end%>
      
     <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <nav class="navbar bg-primary d-flex">
        <a class="navbar-brand">Home</a>
        <div>
          <div class="navbar-nav d-flex flex-row">
            <% if current_user %>
              <h5 class="m-1">Logged in as <%= current_user.name %></h5>
              <p class="m-1"><%= link_to "Log Out", signout_path %></p>
            <% else %>
              <%= link_to "Sign Up", signup_path, class:"p-3" %>
              <%= link_to "Log In", login_path, class:"p-3" %>
            <% end %>
          </div>
        </div>
      </nav>
      
      <%= console %>
    <%= yield %>
    <p id=”notice”><%= notice %></p>
  </body>
</html>

app/views/user/new.html.erb
<h1>Sign up</h1>
<% form_with model: @user do |f| %>
  <%= f.text_field :name %>
  <%= f.submit "Create User" %>
<% end %>

app/views/users/new.html.erb
<h1>Sing up</h1>

<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit "Create User" %>
<% end %>

app/views/users/show.html.erb
<%
=begin%>
 <p id=”notice”><%= notice %></p> 
<%
=end%>
<div class="container">
  <h1><%= current_user.name %></h1>
  <button><%= link_to 'Create Event', new_event_path %></button>

<ul>
  <% if current_user.events.empty? %>
    <p>User has no events created</p> 
  <% else %>
  <h3 class = "card-title"> Past Events</h3>
    <% current_user.events.each do |event| %>

      <% if event.date < Time.now %>
        <li><%= link_to event.name, event %></li>
        <p class = "card-text ">Description: <%= event.description %> </p>
      <% elsif current_user.events.empty? %>
        <p> No past events found </p>
      <% end %>

     <% end %>

     <h3 class = "card-title"> Upcoming Events</h3>

     <% current_user.events.each do |event|%>

      <% if event.date > Time.now %>
        <li><%= link_to event.name, event %></li>
        <p class = "card-text ">Description: <%= event.description %> </p>
      <% elsif current_user.events.empty?  %>
        <p> No future events found </p>
      <% end %>

     <% end%>
  <% end %>
</ul>
</div>